apiVersion: v1
kind: ServiceAccount
metadata:
  name: img-updater
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-reader
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
- kind: ServiceAccount
  name: img-updater
  namespace: img-updater
roleRef:
  kind: ClusterRole
  name: config-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: img-updater
  labels:
    app: img-updater
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: img-updater
          restartPolicy: OnFailure
          containers:
          - name: img-updater
            image: ghcr.io/dodbham-gitops/img-updater-bot:main-42478c35-1650271582
            env:
            - name: KUBECONFIG 
              valueFrom:
                secretKeyRef:
                  name: kubeconfig
                  key: KUBECONFIG
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: git-token
                  key: GIT_TOKEN
            - name: POLICY_NAME
              value: "rust"
            - name: CONFIG_NAME 
              value: "img-updater-config"
            - name: GIT_URL 
              value: "https://github.com"
